import {
  DEFAULT_TEXT_STYLE,
  DEFAULT_TRANSFORM,
  PRISMDECK_SCHEMA_VERSION,
  type LoadedDeck,
} from 'prismdeckjs';

export function createDemoDeck(): LoadedDeck {
  return {
    document: {
      schemaVersion: PRISMDECK_SCHEMA_VERSION,
      id: 'welcome-deck',
      kind: 'presentation',
      metadata: {
        title: 'Spatial ideas, clearly presented',
        author: 'PrismDeckJS',
        sourceFormat: 'native',
      },
      size: { width: 1600, height: 900 },
      layouts: [
        {
          id: 'layout-hero',
          name: 'Hero statement',
          elements: [
            {
              id: 'layout-kicker',
              type: 'text',
              name: 'Kicker',
              frame: { x: 0.08, y: 0.11, width: 0.45, height: 0.08 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.04 },
              opacity: 1,
              visible: true,
              renderOrder: 1,
              text: 'SECTION LABEL',
              style: { ...DEFAULT_TEXT_STYLE, fontSize: 0.025, fontWeight: 700, color: '#C96942' },
              placeholder: { type: 'subtitle', prompt: 'Section label' },
            },
            {
              id: 'layout-title',
              type: 'text',
              name: 'Title',
              frame: { x: 0.08, y: 0.22, width: 0.65, height: 0.3 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.09 },
              opacity: 1,
              visible: true,
              renderOrder: 2,
              text: 'Your title',
              style: { ...DEFAULT_TEXT_STYLE, fontSize: 0.075, fontWeight: 700, color: '#171311', lineHeight: 1.04 },
              placeholder: { type: 'title', prompt: 'Presentation title' },
            },
          ],
        },
        {
          id: 'layout-statement',
          name: 'Statement + metric',
          elements: [
            {
              id: 'layout-statement-title',
              type: 'text',
              name: 'Statement',
              frame: { x: 0.09, y: 0.12, width: 0.68, height: 0.2 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.05 },
              opacity: 1,
              visible: true,
              renderOrder: 1,
              text: 'A clear statement',
              style: { ...DEFAULT_TEXT_STYLE, fontSize: 0.06, fontWeight: 700, color: '#171311' },
              placeholder: { type: 'title' },
            },
            {
              id: 'layout-metric',
              type: 'shape',
              name: 'Metric card',
              frame: { x: 0.63, y: 0.48, width: 0.25, height: 0.26 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.12, rotationY: -8 },
              opacity: 1,
              visible: true,
              renderOrder: 2,
              thickness: 0.12,
              shape: 'roundedRectangle',
              fill: '#C96942',
              stroke: '#C96942',
              strokeWidth: 0,
              text: '42%',
              textStyle: { ...DEFAULT_TEXT_STYLE, fontSize: 0.095, fontWeight: 700, color: '#FFF9F4', align: 'center', verticalAlign: 'middle' },
              placeholder: { type: 'body', prompt: 'Metric' },
            },
          ],
        },
      ],
      slides: [
        {
          id: 'welcome-slide',
          name: 'Welcome',
          layoutId: 'layout-hero',
          durationMs: 8_000,
          background: '#F3EFE8',
          notes: 'Import a PPTX or ODP to replace this local demo.',
          elements: [
            {
              id: 'welcome-kicker',
              type: 'text',
              name: 'Kicker',
              frame: { x: 0.08, y: 0.11, width: 0.45, height: 0.08 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.05 },
              opacity: 1,
              visible: true,
              renderOrder: 1,
              text: 'PRISMDECK / BROWSER NATIVE',
              style: { ...DEFAULT_TEXT_STYLE, fontSize: 0.025, fontWeight: 700, color: '#A64E2F' },
            },
            {
              id: 'welcome-title',
              type: 'text',
              name: 'Hero title',
              frame: { x: 0.08, y: 0.22, width: 0.64, height: 0.31 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.11, rotationY: 2 },
              opacity: 1,
              visible: true,
              renderOrder: 2,
              thickness: 0.06,
              text: 'Spatial ideas,\nclearly presented.',
              style: { ...DEFAULT_TEXT_STYLE, fontSize: 0.073, fontWeight: 700, color: '#171311', lineHeight: 1.02 },
            },
            {
              id: 'welcome-card',
              type: 'shape',
              name: 'Depth card',
              frame: { x: 0.72, y: 0.2, width: 0.18, height: 0.46 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.18, rotationX: -4, rotationY: -11 },
              opacity: 1,
              visible: true,
              renderOrder: 3,
              thickness: 0.22,
              shape: 'roundedRectangle',
              fill: '#C96942',
              stroke: '#8C3A21',
              strokeWidth: 2,
              text: 'PPTX\nODP\n3D',
              textStyle: { ...DEFAULT_TEXT_STYLE, fontSize: 0.052, fontWeight: 700, color: '#FFF9F4', align: 'center', verticalAlign: 'middle', lineHeight: 1.3 },
            },
            {
              id: 'welcome-rule',
              type: 'shape',
              name: 'Rule',
              frame: { x: 0.08, y: 0.69, width: 0.48, height: 0.012 },
              transform: { ...DEFAULT_TRANSFORM, z: 0.03 },
              opacity: 1,
              visible: true,
              renderOrder: 0,
              shape: 'rectangle',
              fill: '#29221F',
              stroke: '#29221F',
              strokeWidth: 0,
            },
          ],
        },
      ],
    },
    assets: new Map(),
  };
}
